#!/bin/sh

# INIT INFO
# Provides:          multimedia
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Multimedia daemon
# Description:       Multimedia daemon

# Installation:
# sudo cp multimedia-services /etc/init.d/
# sudo update-rc.d multimedia-services defaults
### END INIT INFO

PATH=/usr/local/bin:/bin:/usr/bin
DESC="Multimedia daemon"
USER=fox

case "$1" in
  start)
      docker-compose -f /home/fox/multimedia-services/docker-compose.yml up -d
    ;;
  stop)
      docker-compose -f /home/fox/multimedia-services/docker-compose.yml stop
    ;;
  reload|restart)
    $0 stop && $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart}" >&2
    exit 1
    ;;
esac

exit 0
